### ISSUE TITLE
no rhmap/mongodb on docker hub

### ISSUE THREAD

**Issue by vanloswang** [feedhenry/fh-openshift-templates#16]
There is no 'docker.io/rhmap/mongodb' image on dockerhub now, deploying with the template will always fails for me. So how to deploy feedhenry mbass?

**Comment by vanloswang** [comment]
@jasonmadigan @PhilipGough Please take a look at mongodb container images

**Comment by PhilipGough** [comment]
@vanloswang I've made the image public so you should be able to pull it now. Apologies. Let me know if this resolved the issue.

**Comment by vanloswang** [comment]
@PhilipGough download ok now, Thanks.
